spring.application.name=starterkit
spring.profiles.active=dev

app.jwt.secret=YourSuperSecretKeyForJWTEncryptionThatIsSecureAndLong
app.jwt.expiration=86400000

logging.config=classpath:logback-spring.xml