spring.application.name=starterkit
spring.profiles.active=dev

app.jwt.secret=YourSuperSecretKeyForJWTEncryptionThatIsSecureAndLong
app.jwt.expiration=86400000

logging.config=classpath:logback-spring.xml

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2MB

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework.web=DEBUG
logging.level.org.apache.tomcat=DEBUG


spring.web.resources.static-locations=classpath:/static/,file:uploads/

minio.url=http://localhost:9001
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=starterkit

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springdoc=DEBUG